Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.synced_folder ".", "/vagrant"

  config.vm.define "lwyssS" do |s|
    s.vm.hostname = "lwyssS"
    s.vm.network "private_network", ip: "192.168.56.110"
    s.vm.provider "virtualbox" do |vb|
      vb.name = "lwyssS"
      vb.memory = 1024
      vb.cpus = 1
    end

    s.vm.provision "shell", inline: <<-SHELL
      set -x
      sudo apt-get update
      sudo apt-get install -y build-essential dkms linux-headers-amd64 curl ca-certificates

      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-ip=192.168.56.110" sh -

      while [ ! -f /var/lib/rancher/k3s/server/node-token ]; do
        echo "Waiting for server token..."
        sleep 2
      done

      mkdir -p /home/vagrant/.kube
      sudo cp /etc/rancher/k3s/k3s.yaml /home/vagrant/.kube/config
      sudo chown -R vagrant:vagrant /home/vagrant/.kube
      echo 'export KUBECONFIG=$HOME/.kube/config' >> /home/vagrant/.bashrc

      kubectl apply -f /vagrant/app1.yaml
      kubectl apply -f /vagrant/ingress.yaml
      echo "K3s server is ready"
    SHELL
  end
end
