Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"

  config.vm.define "lwyssS" do |s|
    s.vm.hostname = "lwyssS"
    s.vm.network "private_network", ip: "192.168.56.110"

    s.vm.provider "virtualbox" do |vb|
      vb.name = "lwyssS"
      vb.memory = 512
      vb.cpus = 1
    end
  end

  config.vm.define "lwyssSW" do |sw|
    sw.vm.hostname = "lwyssSW"
    sw.vm.network "private_network", ip: "192.168.56.111"

    sw.vm.provider "virtualbox" do |vb|
      vb.name = "lwyssSW"
      vb.memory = 512
      vb.cpus = 1
    end
  end
end
